public class OverLoading_poly {
    Public void Rupam()
    {
        system.debug('Hi');
    }
Public void Rupam(String N)
    {
        system.debug('Hi'+N);
    }
    Public void Rupam(Integer N)
    {
        system.debug('Hi'+N);
    }

    Public void Rupam(Integer X,Integer Y)
    {
        system.debug('Hi'+x);
    }
Public void Rupam(Integer X,String Y)
    {
        system.debug('Hi'+Y);
    }
}